# Generated by Django 4.0.7 on 2024-12-18 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_alter_teacher_educational_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('classnsecions', models.JSONField(default=dict)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='id',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='educational_background',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=150, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('teachers', models.ManyToManyField(to='student_app.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='ClassNSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.PositiveIntegerField(null=True)),
                ('total_student', models.PositiveIntegerField(default=50)),
                ('room_name', models.CharField(max_length=50)),
                ('guide_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.teacher')),
            ],
        ),
    ]
