# Generated by Django 4.0.7 on 2024-12-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_student_address_student_fees_student_standard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classnsection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='classnsection',
            name='section',
            field=models.CharField(default='A', max_length=2),
        ),
    ]
