# Generated by Django 5.1 on 2025-01-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0006_alter_classnsection_room_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fees',
            field=models.FloatField(blank=True, default=3000.0, null=True),
        ),
    ]
